apiVersion: v1
kind: Service
metadata: 
  name: springboot-example
  labels:
    app: springboot-example
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: springboot-example
